/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module fulladder(i0, i1, ci, s, co);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input ci;
  output co;
  input i0;
  input i1;
  output s;
  NOR _17_ (
    .A(_15_),
    .B(_12_),
    .Y(_11_)
  );
  NAND _18_ (
    .A(_08_),
    .B(_10_),
    .Y(_00_)
  );
  NAND _19_ (
    .A(_15_),
    .B(_12_),
    .Y(_01_)
  );
  NOT _20_ (
    .A(_01_),
    .Y(_02_)
  );
  NOR _21_ (
    .A(_11_),
    .B(_02_),
    .Y(_03_)
  );
  NAND _22_ (
    .A(_00_),
    .B(_01_),
    .Y(_04_)
  );
  NAND _23_ (
    .A(_14_),
    .B(_04_),
    .Y(_05_)
  );
  NAND _24_ (
    .A(_09_),
    .B(_03_),
    .Y(_06_)
  );
  NAND _25_ (
    .A(_05_),
    .B(_06_),
    .Y(_16_)
  );
  NAND _26_ (
    .A(_14_),
    .B(_00_),
    .Y(_07_)
  );
  NAND _27_ (
    .A(_01_),
    .B(_07_),
    .Y(_13_)
  );
  NOT _28_ (
    .A(_15_),
    .Y(_08_)
  );
  NOT _29_ (
    .A(_14_),
    .Y(_09_)
  );
  NOT _30_ (
    .A(_12_),
    .Y(_10_)
  );
  IBUF _31_ (
    .I(ci),
    .O(_12_)
  );
  OBUF _32_ (
    .I(_13_),
    .O(co)
  );
  IBUF _33_ (
    .I(i0),
    .O(_14_)
  );
  IBUF _34_ (
    .I(i1),
    .O(_15_)
  );
  OBUF _35_ (
    .I(_16_),
    .O(s)
  );
endmodule