/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module counter_4bit(clk, rst, en, co, counter);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  input clk;
  output co;
  output [3:0] counter;
  wire \counter_reg[0] ;
  wire \counter_reg[1] ;
  wire \counter_reg[2] ;
  wire \counter_reg[3] ;
  input en;
  input rst;
  NOT _22_ (
    .A(\counter_reg[0] ),
    .Y(_04_)
  );
  NOT _23_ (
    .A(\counter_reg[3] ),
    .Y(_05_)
  );
  NOT _24_ (
    .A(_20_),
    .Y(_06_)
  );
  NAND _25_ (
    .A(\counter_reg[0] ),
    .B(\counter_reg[1] ),
    .Y(_07_)
  );
  NAND _26_ (
    .A(\counter_reg[3] ),
    .B(\counter_reg[2] ),
    .Y(_08_)
  );
  NOR _27_ (
    .A(_07_),
    .B(_08_),
    .Y(_19_)
  );
  NOR _28_ (
    .A(_04_),
    .B(_06_),
    .Y(_09_)
  );
  NOR _29_ (
    .A(\counter_reg[0] ),
    .B(_20_),
    .Y(_10_)
  );
  NOR _30_ (
    .A(_09_),
    .B(_10_),
    .Y(_00_)
  );
  NOR _31_ (
    .A(_06_),
    .B(_07_),
    .Y(_11_)
  );
  NOR _32_ (
    .A(\counter_reg[1] ),
    .B(_09_),
    .Y(_12_)
  );
  NOR _33_ (
    .A(_11_),
    .B(_12_),
    .Y(_01_)
  );
  NAND _34_ (
    .A(\counter_reg[2] ),
    .B(_11_),
    .Y(_13_)
  );
  NOT _35_ (
    .A(_13_),
    .Y(_14_)
  );
  NOR _36_ (
    .A(\counter_reg[2] ),
    .B(_11_),
    .Y(_15_)
  );
  NOR _37_ (
    .A(_14_),
    .B(_15_),
    .Y(_02_)
  );
  NOR _38_ (
    .A(\counter_reg[3] ),
    .B(_14_),
    .Y(_16_)
  );
  NOR _39_ (
    .A(_05_),
    .B(_13_),
    .Y(_17_)
  );
  NOR _40_ (
    .A(_16_),
    .B(_17_),
    .Y(_03_)
  );
  DFF_PP0 _41_ (

    .D(_00_),
    .Q(\counter_reg[0] ),
    .R(_21_)
  );
  DFF_PP0 _42_ (

    .D(_01_),
    .Q(\counter_reg[1] ),
    .R(_21_)
  );
  DFF_PP0 _43_ (

    .D(_02_),
    .Q(\counter_reg[2] ),
    .R(_21_)
  );
  DFF_PP0 _44_ (

    .D(_03_),
    .Q(\counter_reg[3] ),
    .R(_21_)
  );
  IBUF _45_ (
    .I(clk),
    .O(_18_)
  );
  OBUF _46_ (
    .I(_19_),
    .O(co)
  );
  OBUF _47_ (
    .I(\counter_reg[0] ),
    .O(counter[0])
  );
  OBUF _48_ (
    .I(\counter_reg[1] ),
    .O(counter[1])
  );
  OBUF _49_ (
    .I(\counter_reg[2] ),
    .O(counter[2])
  );
  OBUF _50_ (
    .I(\counter_reg[3] ),
    .O(counter[3])
  );
  IBUF _51_ (
    .I(en),
    .O(_20_)
  );
  IBUF _52_ (
    .I(rst),
    .O(_21_)
  );
endmodule