/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module fulladder(i0, i1, ci, s, co);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input ci;
  output co;
  input i0;
  input i1;
  output s;
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _17_ (
    .in1({ _15_, _12_ }),
    .out1(_11_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _18_ (
    .in1({ _08_, _10_ }),
    .out1(_00_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _19_ (
    .in1({ _15_, _12_ }),
    .out1(_01_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _20_ (
    .in1(_01_),
    .out1(_02_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _21_ (
    .in1({ _11_, _02_ }),
    .out1(_03_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _22_ (
    .in1({ _00_, _01_ }),
    .out1(_04_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _23_ (
    .in1({ _14_, _04_ }),
    .out1(_05_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _24_ (
    .in1({ _09_, _03_ }),
    .out1(_06_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _25_ (
    .in1({ _05_, _06_ }),
    .out1(_16_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _26_ (
    .in1({ _14_, _00_ }),
    .out1(_07_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _27_ (
    .in1({ _01_, _07_ }),
    .out1(_13_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _28_ (
    .in1(_15_),
    .out1(_08_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _29_ (
    .in1(_14_),
    .out1(_09_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _30_ (
    .in1(_12_),
    .out1(_10_)
  );
  pin #(
    .n(32'sd1)
  ) _31_ (
    .in1(ci),
    .out1(_12_)
  );
  pout #(
    .n(32'sd1)
  ) _32_ (
    .in1(_13_),
    .out1(co)
  );
  pin #(
    .n(32'sd1)
  ) _33_ (
    .in1(i0),
    .out1(_14_)
  );
  pin #(
    .n(32'sd1)
  ) _34_ (
    .in1(i1),
    .out1(_15_)
  );
  pout #(
    .n(32'sd1)
  ) _35_ (
    .in1(_16_),
    .out1(s)
  );
endmodule
