# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.runs/synth_1/.Xil/Vivado-3552-LAPTOP-7B6MG8B6/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/CLA.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/CLA17.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/Booth_MUL.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/RCA.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/Radix2_DIV.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/Radix4_MUL.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/SAYAC_DPB.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/SAYAC_CCU.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/SAYAC_TRF.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/SAYAC_TRB.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/SAYAC_DPU.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/SAYAC_MEM.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/SAYAC_inst_ROM.vhd
      C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.srcs/sources_1/imports/ASIC_modules/SAYAC_TOP.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top SAYAC_TOP
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/mahbo/OneDrive/Documents/GitHub/SAYAC-Embedded-Processor/Synth/SAYAConPYNQ/SAYAConPYNQ.runs/synth_1/.Xil/Vivado-3552-LAPTOP-7B6MG8B6/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    rt::close_pss_mem_watcher
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
